### ISSUE TITLE
Ender Dragon allows multiple kills using high-tier multishot bow

### ISSUE THREAD

**Issue by Xevion** [xt9/DeepMobLearning#49] opened 2019-08-10 06:30 UTC
I have found the most convenient way to completely destroy the mechanics of the Enderdragon data model. Perhaps it extends to other mobs/animals if the multishot can hit them during their death animation.

Demonstration of me leveling a brand new Ender Dragon data model from Faulty to Superior and a half with a single Ender Dragon:

**YouTube Video**
[![image](https://user-images.githubusercontent.com/44609630/62818476-4cdc8480-bb0d-11e9-9383-24cb2ffaf2fe.png)](https://youtu.be/RECYaaQfAcU)

**Bow Specs** (if you want to reproduce fully)
![image](https://user-images.githubusercontent.com/44609630/62818491-9331e380-bb0d-11e9-91c9-5d03f83b60f5.png)

All I do is kill the dragon, and then continuously shoot it. Multishot IV makes each barrage of arrows count as a kill multiple times, ensuring that not only does the Enderdragon count for multiple kills, but for dozens of kills.

---

Modpack: `Antimatter Chemistry 1.2.17`
Mod Version: `deepmoblearning-1.12.2-2.5.2-universal.jar`
OS: Windows 10

**Comment by xt9** [comment] 2020-05-25 15:29
duplicate of #21

**Closed by xt9** 2020-05-25 15:29 UTC
